# Generated by Django 3.1.7 on 2021-04-17 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFarmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='locationX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locationY',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('farmName', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('farmerPoint', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('locationY', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
