# Generated by Django 3.1.7 on 2021-04-18 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('locationX', models.FloatField(default=0)),
                ('locationY', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature', models.FloatField(default=0)),
                ('key', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentCompany',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectDelivery',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('shipmentCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.shipmentcompany')),
                ('shippingAddress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='BoxDelivery',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.box')),
                ('shipmentCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.shipmentcompany')),
                ('shippingAddress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
