# Generated by Django 3.1.7 on 2021-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_box_boxdelivery_directdelivery_shipmentcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmPicture',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmerPicture',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
