# Generated by Django 3.1.7 on 2021-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210418_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='farmproduct',
            name='_id',
        ),
        migrations.AddField(
            model_name='product',
            name='harvestTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productionTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='farmName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='farmPicture',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='farmerPicture',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='farmerPoint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='AnimalProduct',
        ),
        migrations.DeleteModel(
            name='farmer',
        ),
        migrations.DeleteModel(
            name='FarmProduct',
        ),
    ]
