# Generated by Django 3.1.7 on 2021-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210504_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvestTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productionTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
