# Generated by Django 3.1.7 on 2021-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210518_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit',
            field=models.FloatField(default=0),
        ),
    ]
