# Generated by Django 3.1.7 on 2021-06-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farmerPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
