# Generated by Django 3.1.7 on 2021-06-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_product_isfarmproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderqr',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
