# Generated by Django 3.1.7 on 2021-06-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_order_orderqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
