# Generated by Django 3.1.7 on 2021-06-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_user_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distance',
        ),
        migrations.AddField(
            model_name='product',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
